//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Client
    {
        public int ClientID { get; set; }
        public string Name { get; set; }
        public bool IsFeeGenerationAuto { get; set; }
        public bool PaymentModeBank { get; set; }
        public bool PaymentModeCash { get; set; }
    }
}
