//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_PermissionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AT_PermissionGroup()
        {
            this.AT_PermissionGroupJunc = new HashSet<AT_PermissionGroupJunc>();
            this.AT_UserExtraPermissionjunc = new HashSet<AT_UserExtraPermissionjunc>();
        }
    
        public int PermissionGroupID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int ClientID { get; set; }
        public bool IsExtrapermission { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AT_PermissionGroupJunc> AT_PermissionGroupJunc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AT_UserExtraPermissionjunc> AT_UserExtraPermissionjunc { get; set; }
    }
}
