//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AT_Pages()
        {
            this.AT_Permission = new HashSet<AT_Permission>();
        }
    
        public int PageID { get; set; }
        public int ModuleID { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> PageOrder { get; set; }
        public bool IsActive { get; set; }
        public string PageIcon { get; set; }
        public bool ShowOnMenu { get; set; }
        public string Controller { get; set; }
    
        public virtual AT_Modules AT_Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AT_Permission> AT_Permission { get; set; }
    }
}
