//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_RolePermissionJunc
    {
        public long RolePermissionJuncID { get; set; }
        public int PermissionID { get; set; }
        public int RoleID { get; set; }
        public bool IsGroup { get; set; }
        public int ClientID { get; set; }
    
        public virtual AT_Role AT_Role { get; set; }
    }
}
