//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_UserExtraPermissionjunc
    {
        public int UserExtraPermissionjuncID { get; set; }
        public int ClientID { get; set; }
        public int UserID { get; set; }
        public int PermissionGroupID { get; set; }
    
        public virtual AT_PermissionGroup AT_PermissionGroup { get; set; }
        public virtual AT_Users AT_Users { get; set; }
    }
}
