//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AT_Client> AT_Client { get; set; }
        public virtual DbSet<AT_Modules> AT_Modules { get; set; }
        public virtual DbSet<AT_Pages> AT_Pages { get; set; }
        public virtual DbSet<AT_Permission> AT_Permission { get; set; }
        public virtual DbSet<AT_PermissionActionJunc> AT_PermissionActionJunc { get; set; }
        public virtual DbSet<AT_PermissionGroup> AT_PermissionGroup { get; set; }
        public virtual DbSet<AT_PermissionGroupJunc> AT_PermissionGroupJunc { get; set; }
        public virtual DbSet<AT_Role> AT_Role { get; set; }
        public virtual DbSet<AT_RolePermissionJunc> AT_RolePermissionJunc { get; set; }
        public virtual DbSet<AT_UserExtraPermissionjunc> AT_UserExtraPermissionjunc { get; set; }
        public virtual DbSet<AT_Users> AT_Users { get; set; }
        public virtual DbSet<Benefit> Benefits { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Resign> Resigns { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
