//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;




public class PermissionEnum
{
    
    public const string ManagePages = "ManagePages";
    
    public const string ManagePermission = "Manage Permission";
    
    public const string OpenCRMSettings = "Open CRM Settings";
    
    public const string ManageUsers = "Manage Users";
    
    public const string ManageRoles = "Manage Roles";
    
    public const string ManageGroupPermission = "Manage Group Permission";
    
    public const string ManageUserProfile = "Manage UserProfile";
    
    public const string ManageStudent = "Manage Student";
    
    public const string ManageClass = "ManageClass";
    
    public const string ManageSection = "ManageSection";
    
    public const string ManageSession = "ManageSession";
    
    public const string ManageStudentTransfer = "Manage Student Transfer";
    
    public const string FeeChallan = "FeeChallan";
    
    public const string ManageFeeType = "ManageFeeType";
    
    public const string ManageFeesPosting = "ManageFeesPosting";
    
    public const string CustomFeeTypeCrud = "CustomFeeTypeCrud";
    
    public const string ManageFeeStructure = "ManageFeeStructure";
    
    public const string Unknown = "Unknown";
    
    public const string DashboardPer = "DashboardPer";
    
    public const string MBranch = "MBranch";
}
